// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package forwarding

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ForwardingServiceClient is the client API for ForwardingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForwardingServiceClient interface {
	ForwardLogicalRequest(ctx context.Context, in *ForwardedLogicalRequest, opts ...grpc.CallOption) (*ForwardedLogicalResponse, error)
}

type forwardingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewForwardingServiceClient(cc grpc.ClientConnInterface) ForwardingServiceClient {
	return &forwardingServiceClient{cc}
}

func (c *forwardingServiceClient) ForwardLogicalRequest(ctx context.Context, in *ForwardedLogicalRequest, opts ...grpc.CallOption) (*ForwardedLogicalResponse, error) {
	out := new(ForwardedLogicalResponse)
	err := c.cc.Invoke(ctx, "/forwarding.ForwardingService/ForwardLogicalRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForwardingServiceServer is the server API for ForwardingService service.
// All implementations must embed UnimplementedForwardingServiceServer
// for forward compatibility
type ForwardingServiceServer interface {
	ForwardLogicalRequest(context.Context, *ForwardedLogicalRequest) (*ForwardedLogicalResponse, error)
	mustEmbedUnimplementedForwardingServiceServer()
}

// UnimplementedForwardingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedForwardingServiceServer struct {
}

func (UnimplementedForwardingServiceServer) ForwardLogicalRequest(context.Context, *ForwardedLogicalRequest) (*ForwardedLogicalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardLogicalRequest not implemented")
}
func (UnimplementedForwardingServiceServer) mustEmbedUnimplementedForwardingServiceServer() {}

// UnsafeForwardingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForwardingServiceServer will
// result in compilation errors.
type UnsafeForwardingServiceServer interface {
	mustEmbedUnimplementedForwardingServiceServer()
}

func RegisterForwardingServiceServer(s grpc.ServiceRegistrar, srv ForwardingServiceServer) {
	s.RegisterService(&ForwardingService_ServiceDesc, srv)
}

func _ForwardingService_ForwardLogicalRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardedLogicalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForwardingServiceServer).ForwardLogicalRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/forwarding.ForwardingService/ForwardLogicalRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForwardingServiceServer).ForwardLogicalRequest(ctx, req.(*ForwardedLogicalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForwardingService_ServiceDesc is the grpc.ServiceDesc for ForwardingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForwardingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "forwarding.ForwardingService",
	HandlerType: (*ForwardingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForwardLogicalRequest",
			Handler:    _ForwardingService_ForwardLogicalRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helper/forwarding/forwarding.proto",
}
